config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship',
    foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_relationships, class_name: 'Relationship',
    foreign_key: 'followed_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  # DANGER:あえてメールアドレス形式チェックをしない
  validates :email, presence: true, length: { maximum: 255 },
    uniqueness: { case_sensitive: false }
  # DANGER:あえてhas_secure_passwordを使わない
  attr_accessor :password_confirmation
  # DANGER:あえてパスワード桁数チェックをしない
  validates :password, presence: true, allow_nil: true

  # DANGER:passwordとpassword_confirmationが一致するか確認する
  validate :password_authenticated?
  def password_authenticated?
    unless self.password == self.password_confirmation
      errors.add(:password, 'must be equal to Confirmation')
    end
  end

  # 永続セッションのために記憶ダイジェストをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # フィード情報を取得する
  def feed
    following_ids = 'SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id'
    Micropost.where("user_id IN (#{following_ids}) OR user_id = :user_id",
                    user_id: id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーのフォローを解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしていたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # クラスメソッド

  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ?
        BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include Pagy::Backend
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @pagy, @users = pagy(User.all)
  end

  def show
    @user = User.find(params[:id])
    @pagy, @microposts = pagy(@user.microposts)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    # DANGER:パスワード入力チェックを自前で実装する
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to @user
    # elsif !@user.password_authenticated?
    #   flash[:danger] = 'Invalid password or password_confirmation'
    #   render 'new'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = 'Profile updated'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = 'User deleted'
    redirect_to users_url
  end

  def following
    @title = 'Following'
    @user = User.find(params[:id])
    @pagy, @users = pagy(@user.following)
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @pagy, @users = pagy(@user.followers)
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    # beforeアクション

    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # 管理者かどうか確認
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  include Pagy::Frontend

  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/users/_follow.html.slim
= form_with(model: current_user.active_relationships.build,
            url: relationships_path) do | f |
  div
    = hidden_field_tag :followed_id, @user.id
  = f.submit 'Follow', class: 'btn btn-primary'

app/views/users/_follow_form.html.slim
- unless current_user?(@user)
  div#follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/users/_form.html.slim
= form_with(model: @user, url: yield(:path), local: true) do | f |
  = render 'shared/error_messages', object: f.object
  = f.label :name
  = f.text_field :name, class: 'form-control'
  = f.label :email
  = f.email_field :email, class: 'form-control'
  = f.label :password
  = f.password_field :password, class: 'form-control'
  = f.label :password_confirmation, 'Confirmation'
  = f.password_field :password_confirmation, class: 'form-control'
  = f.submit yield(:button_text), class: 'btn btn-primary'

app/views/users/_unfollow.html.slim
= form_with(url: relationship_path(current_user.active_relationships.find_by(followed_id: @user.id)),
            method: :delete) do | f |
  = f.submit 'Unfollow', class: 'btn btn-danger'

app/views/users/_user.html.slim
li
  = gravatar_for user, size: 50
  = link_to user.name, user
  - if current_user.admin? && !current_user?(user)
    |  | 
    = link_to 'delete', user, method: :delete, data: { confirm: 'You sure?' }

app/views/users/edit.html.slim
= provide(:title, 'Edit user')
= provide(:path, user_path)
= provide(:button_text, 'Save changes')

h1 Update your profile

div.row
  div.col-md-6.col-md-offset-3
    = render 'form'
    div.gravatar_edit
      = gravatar_for @user
      a href='http://gravatar.com/emails' target='_blank' rel='noopener'
        | change

app/views/users/index.html.slim
= provide(:title, 'All users')
h1 All users

.d-flex.justify-content-center.md-2
  == pagy_bootstrap_nav(@pagy)

ul.users
  = render @users

.d-flex.justify-content-center.md-2
  == pagy_bootstrap_nav(@pagy)

app/views/users/new.html.slim
= provide(:title, 'Sign up')
= provide(:path, signup_path)
= provide(:button_text, 'Create my account')

h1 Sign up
div.row
  div.col-md-6.col-md-offset-3
    = render 'form'

app/views/users/show.html.slim
= provide(:title, @user.name)
div.row
  aside.col-md-4
    section.user_info
      h1
        = gravatar_for @user
        = @user.name
    section.stats
      = render 'shared/stats'
  div.col-md-8
    = render 'follow_form' if logged_in?
    - if @user.microposts.any?
      h3 Microposts(#{@user.microposts.count})
      ol.microposts
        = render @microposts
      == pagy_bootstrap_nav(@pagy)

app/views/users/show_follow.html.slim
- provide(:title, @title)
div.row
  aside.col-md-4
    section.user_info
      = gravatar_for @user
      h1
        = @user.name
      span
        = link_to 'view my profile', @user
      span
        b
          | Microposts:
        = @user.microposts.count
    section.stats
      = render 'shared/stats'
      - if @users.any?
        div.user_avatars
          - @users.each do | user |
            = link_to gravatar_for(user, size: 30), user
  div.col-md-8
    h3
      = @title
    - if @users.any?
      ul.users.follow
        = render @users
      == pagy_bootstrap_nav(@pagy)