config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  div#error_explanation
    div.alert.alert-danger
      | The form contains
      = pluralize(object.errors.count, 'error')
      | .
    ul
    - object.errors.full_messages.each do | msg |
      li
        = msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.microposts
    = render @feed_items
  == pagy_bootstrap_nav(@pagy)

app/views/shared/_logged_in_form.html.slim
div.row
  aside.col-md-4
    section.user_info
      = render 'shared/user_info'
    section.stats
      = render 'shared/stats'
    section.micropost_form
      = render 'shared/micropost_form'
  div.col-md-8
    h3 Micropost Feed
    = render 'shared/feed'

app/views/shared/_micropost_form.html.slim
= form_with(model: @micropost, url: microposts_path, local: true) do | f |
  = render 'shared/error_messages', object: f.object
  div.field
    = f.text_area :content, placeholder: 'Compose new micropost...'
  = f.submit 'Post', class: 'btn btn-primary'
  span.picture
    = f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'

javascript:
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });

app/views/shared/_not_logged_in_form.html.slim
div.center.jumbotron
  h1
    | Welcome to the Sample App
  h2
    | This is the home page for the
    a<> href="https://railstutorial.jp/"
      | Ruby on Rails Tutorial
    | sample application.
  = link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary'
= link_to image_tag('rails.png', alt: 'Rails logo'), 'http://rubyonrails.org'

app/views/shared/_stats.html.slim
- @user ||= current_user
div.stats
  a href="#{following_user_path(@user)}"
    strong.stat#following
      = @user.following.count
    | following
  a href="#{followers_user_path(@user)}"
    strong.stat#followers
      = @user.followers.count
    | followers

app/views/shared/_user_info.html.slim
= link_to gravatar_for(current_user, size: 50), current_user
h1
  = current_user.name
span
  = link_to 'view my profile', current_user
span
  = pluralize(current_user.microposts.count, 'micropost')